import {Text, View, Image, StyleSheet, TextInput, Alert} from 'react-native';
import React, {useState, version} from 'react';
import {useNavigation, useRoute} from '@react-navigation/native';
import {CreateNavigationProp, CreateRouteProp} from '../../types/navigation';
import colors from '../../theme/colors';
import Button from '../../components/Button';
import {useMutation} from '@apollo/client';
import {createPost} from './queries';
import {CreatePostMutation, CreatePostMutationVariables} from '../../API';
import {useAuthContext} from '../../contexts/AuthContext';
import Carousel from '../../components/Carousel';
import VideoPlayer from '../../components/VideoPlayer';

const CreatePostScreen = () => {
  const [description, setDescription] = useState('');
  const {userId} = useAuthContext();
  const navigation = useNavigation<CreateNavigationProp>(); //CreateNavigationProp removes error on popToTop

  const route = useRoute<CreateRouteProp>();
  const {image, images, video} = route.params;

  let content = null;
  if (image) {
    content = (
      <Image
        style={styles.image}
        source={{
          uri: image,
        }}
      />
    );
  } else if (images) {
    content = <Carousel images={images} />;
  } else if (video) {
    content = <VideoPlayer uri={video} paused={false} />;
  }

  const [doCreatePost] = useMutation<
    CreatePostMutation,
    CreatePostMutationVariables
  >(createPost);

  const submit = async () => {
    //id will be autogenerated
    try {
      const response = await doCreatePost({
        variables: {
          input: {
            type: 'POST',
            description,
            image: image,
            images: images,
            video: video,
            noOfComments: 0,
            noOfLikes: 0,
            userID: userId,
          },
        },
      });
      console.log(response);
      navigation.popToTop(); //First move to camera,so to go to the top screen of UploadStack when you move back to it
      navigation.navigate('HomeStack'); //Than to homeScreen
    } catch (e) {
      Alert.alert('Error uploading the post', (e as Error).message);
    }
  };

  return (
    <View style={styles.root}>
      <View style={styles.content}>{content}</View>
      <TextInput
        value={description}
        placeholder="Description..."
        onChangeText={setDescription}
        style={styles.input}
        multiline
        numberOfLines={5}
      />
      <Button text="Submit" onPress={submit} />
    </View>
  );
};

const styles = StyleSheet.create({
  root: {
    alignItems: 'center',
    padding: 10,
  },
  image: {
    width: 200,
    height: 200,
  },
  input: {
    marginVertical: 10,
    alignSelf: 'stretch',
    backgroundColor: colors.white,
    padding: 10,
  },
  content: {
    width: '100%',
    aspectRatio: 1,
  },
});
export default CreatePostScreen;
