name: EAS Build

on:
  workflow_dispatch:

  push:
    branches:
      - staging
      - dev # TODO Remove when we are done

jobs:
  build-android:
    name: Install and build android app (Preview)
    uses: ./.github/workflows/eas-build.yaml # navigate to root github than specific workflow
    secrets: inherit # pass all secrets from deploy to eas build
    with:
      PLATFORM: android
      PROFILE: preview

  build-ios:
    name: Install and build ios app (Preview)
    uses: ./.github/workflows/eas-build.yaml # navigate to root github than specific workflow
    secrets: inherit # pass all secrets from deploy to eas build
    with:
      PLATFORM: ios
      PROFILE: preview
