name: EAS Build

on:
  workflow_dispatch:

  push:
    branches:
      - staging
      - dev # TODO Remove when we are done

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AMPLIFY_FACEBOOK_CLIENT_ID: ${{ secrets.AMPLIFY_FACEBOOK_CLIENT_ID }}
  AMPLIFY_FACEBOOK_CLIENT_SECRET: ${{ secrets.AMPLIFY_FACEBOOK_CLIENT_SECRET }}
  AMPLIFY_GOOGLE_CLIENT_ID: ${{ secrets.AMPLIFY_GOOGLE_CLIENT_ID }}
  AMPLIFY_GOOGLE_CLIENT_SECRET: ${{ secrets.AMPLIFY_GOOGLE_CLIENT_SECRET }}

jobs:
  deploy-backend: #deploy amplify back end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # copy from build in eas-build to get code from our repository

      - uses: actions/setup-node@v3 # copy from build in eas-build to get code from our repository
        with:
          node-version: 16.x
          cache: npm

      # Install and configure AWS cli
      - name: Install AWS cli
        run:
          | #pipe represent running multiple commands. Note we added --update at the end
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS cli credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
          aws configure set default.region $AWS_REGION

      # Install and configure AWS Amplify cli
      - name: Install AWS Amplify cli
        run: |
          npm install -g --unsafe-perm @aws-amplify/cli@latest
          echo "amplify version $(amplify --version)"

      # Initialize the backend environment
      - name: Initialize backend environment
        run: ./.github/scripts/amplify-init.sh staging

      # Push changes to cloud
      - name: Push backend changes
        run: amplify push --yes # would generate a couple of changes in our code

      # Commit and push changes to github - we can use an action already defined Git Auto Commit from marketplace
      - uses: stefanzweifel/git-auto-commit-action@v4

  build-android:
    name: Install and build android app (Development)
    needs: deploy-backend
    uses: ./.github/workflows/eas-build.yaml # navigate to root github than specific workflow
    secrets: inherit # pass all secrets from deploy to eas build
    with:
      PLATFORM: android
      PROFILE: development

  build-ios:
    name: Install and build ios app (Development)
    needs: deploy-backend
    uses: ./.github/workflows/eas-build.yaml # navigate to root github than specific workflow
    secrets: inherit # pass all secrets from deploy to eas build
    with:
      PLATFORM: ios
      PROFILE: development
