name: EAS Build

on:
  workflow_call: #triggered when called and not manual or pushed
    inputs:
      PLATFORM:
        required: true
        type: string
      PROFILE:
        required: false
        type: string
        default: production # if we not sending the profile input variables(required: false) it would default to "production"

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        run: eas build --profile ${{ inputs.PROFILE }} --platform {{ inputs.PLATFORM }} --non-interactive # Note the profile is dynamically called from the inputs now
